theme: jekyll-theme-cayman
title: "Projet sur la dynamique des Pokemons"
description: "-Julie CHARLES -Léandre POUPINEL -Nahidath GASSA -Neevath RAVICHANDRAN"
webrick:
  headers:
    journal:  https://are-dynamic-2018.github.io/Dynamique-des-Pokemons/Journal%20de%20bord
  
